version: "3.8"
services: 
  osp-navigate:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./src:/navigate/src:ro
    environment:
      - CHOKIDAR_USEPOLLING=true